import { Template } from '../types/template.type';
import { TemplateType } from '../enums/templateType.enum';

export const templates: Template[] = [
  {
    id: 1,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 2000,
    height: 3000,
    resolution: 300,
  },
  {
    id: 2,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 400,
  },
  {
    id: 3,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 4,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 5,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 6,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 7,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 8,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 9,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 10,
    title: 'Custom',
    type: TemplateType.Recent,
    width: 1080,
    height: 1090,
    resolution: 300,
  },
  {
    id: 11,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
  {
    id: 12,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
  {
    id: 13,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
  {
    id: 14,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
  {
    id: 15,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
  {
    id: 16,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
  {
    id: 17,
    title: 'Photo',
    type: TemplateType.Photo,
    width: 2000,
    height: 1090,
    resolution: 300,
  },
];
